FROM denoland/deno:alpine

WORKDIR /app

RUN apk add --no-cache libstdc++

COPY ./src /app/src
COPY ./config /app/config
COPY ./database /app/database

COPY ./deno.* /app/
COPY ./*.ts /app/


COPY ./entrypoint.sh /app/
RUN chmod +x /app/entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["/app/entrypoint.sh"]
