import {
  compensationType,
  coopCycleType,
  coopYearType,
  decisionType,
  offerStatusType,
  programLevelType,
  sourceType,
} from "./enums.ts";
import {
  companyRelations,
  locationRelations,
  majorRelations,
  minorRelations,
  positionRelations,
  submissionMajorRelations,
  submissionMinorRelations,
  submissionRelations,
} from "./relations.ts";
import {
  company,
  compensation,
  location,
  major,
  minor,
  position,
  submission,
  submissionMajor,
  submissionMinor,
} from "./table.ts";

export const schema = {
  sourceType,
  coopYearType,
  coopCycleType,
  decisionType,
  offerStatusType,
  programLevelType,
  submissionMinorRelations,
  submissionMajorRelations,
  positionRelations,
  minorRelations,
  majorRelations,
  locationRelations,
  submissionRelations,
  companyRelations,
  company,
  position,
  compensation,
  compensationType,
  location,
  major,
  minor,
  submission,
  submissionMajor,
  submissionMinor,
};

export const organizedSchemas = {
  enums: {
    sourceType,
    coopYearType,
    coopCycleType,
    decisionType,
    offerStatusType,
    programLevelType,
  },
  relations: {
    submissionMinorRelations,
    submissionMajorRelations,
    positionRelations,
    minorRelations,
    majorRelations,
    locationRelations,
    submissionRelations,
    companyRelations,
  },
  tables: {
    company,
    compensation,
    compensationType,
    location,
    major,
    minor,
    submission,
    submissionMajor,
    submissionMinor,
  },
};
